# fly.toml app configuration file generated for api-nodejs-guq5qq on 2025-09-16T16:47:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-nodejs-guq5qq'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
